name: CI/CD Pipeline

on: 
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        #Step-1: Checkout the repo
        - name: Checkout code
          uses: actions/checkout@v4
        #Step-3: Login to dockerhub
        - name: Log in to Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        #Step-4: Build docker image
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
        #Step-5: Push image to Dockerhub
        - name: Push image to Dockerhub
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
        #Step-6: Run the container
        - name: Run container
          run: |
            docker run -d -p 5000:5000 --name flask-container ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
            docker ps -a
        


